rpms:
  - zenity
  - tailscale
  - gnome-shell-extension-appindicator
  - gnome-shell-extension-just-perfection
  - gnome-shell-extension-blur-my-shell
flatpaks:
  - org.mozilla.firefox
  - com.mattjakeman.ExtensionManager
  - org.gustavoperedo.FontDownloader
  - com.github.tchx84.Flatseal
  - io.github.celluloid_player.Celluloid
